tsdf_voxel_size: 0.20
tsdf_voxels_per_side: 16
color_mode: "color"
use_tf_transforms: true
verbose: true
update_mesh_every_n_sec: 0.5
min_time_between_msgs_sec: 0.0
slice_level: 1.0
max_ray_length_m: 15.0
min_ray_length_m: 0.1
max_weight: 10000.0
use_const_weight: true
allow_clear: true
mesh_min_weight: 0.001
use_masked_tsdf_updates: false
max_consecutive_ray_collisions: 1
clear_checks_every_n_frames: 1